[project]
name = "aioschwab"
version = "0.0.0"
description = "Simple asynchronous HTTP python framework for Schwab Individual Trader API at server side"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=7.0.1",
    "jupyter>=1.1.1",
    "websockets>=15.0.1",
]
